// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20231102151024_InitProducts")]
    partial class InitProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductLib.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Id");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint")
                        .HasColumnName("Category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("LastUpdatedOn");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ca1c1ed8-b2d1-430b-a184-a61d13ac3b70",
                            Category = (byte)1,
                            Code = "PRD001",
                            CreatedOn = new DateTime(2023, 11, 2, 22, 10, 24, 441, DateTimeKind.Local).AddTicks(3728),
                            Name = "Coca"
                        },
                        new
                        {
                            Id = "32295a53-e8ae-4207-8e94-987c78d94da8",
                            Category = (byte)32,
                            Code = "PRD002",
                            CreatedOn = new DateTime(2023, 11, 2, 22, 10, 24, 441, DateTimeKind.Local).AddTicks(3746),
                            Name = "Dream 125"
                        },
                        new
                        {
                            Id = "117721dd-75f1-4d90-9d2b-3e209c5e90d8",
                            Category = (byte)4,
                            Code = "PRD003",
                            CreatedOn = new DateTime(2023, 11, 2, 22, 10, 24, 441, DateTimeKind.Local).AddTicks(3750),
                            Name = "TShirt-SEA game 2023"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
